### ISSUE TITLE
error when trying to fetch fanarts

### ISSUE THREAD

**Issue by chewiiie** [pkscout/script.artistslideshow#48] opened 2018-03-28 12:45 UTC
Hi
I'm getting the error below when the plugin tries to fetch fanarts. it download 1 or 2 and then I get this error.
Kodi is 17.6 with everything uptodate. Installed on a windows 10 64bits PC.

14:29:48.964 T:896  NOTICE: NEXTUP SERVICE NOTIFICATION Service -> Starting NextUp Service
14:29:48.965 T:896  NOTICE: NEXTUP SERVICE NOTIFICATION Service -> ========  START NEXTUP SERVICE NOTIFICATION  ========
14:29:48.966 T:896  NOTICE: NEXTUP SERVICE NOTIFICATION Service -> KODI Version: 17.6 Git:20171114-a9a7a20
14:29:48.981 T:896  NOTICE: NEXTUP SERVICE NOTIFICATION Service -> NEXTUP SERVICE NOTIFICATION Version: 1.0.37
14:29:49.742 T:9008 WARNING: Skin has invalid include:
14:29:50.205 T:3028 WARNING: Previous line repeats 2 times.
14:29:50.205 T:3028  NOTICE: plugin.audio.spotify --> Logged in to Spotify - Username: chewiiie
14:30:15.632 T:12052 WARNING: CWin32DirectSound::GetSpace - buffer underrun - W:40464, P:29576, O:37016.
14:30:15.657 T:12052 WARNING: CWin32DirectSound::GetSpace - buffer underrun - W:51048, P:38488, O:40464.
14:30:16.174 T:12052 WARNING: CWin32DirectSound::GetSpace - buffer underrun - W:44136, P:30752, O:40472.
14:30:16.201 T:12052 WARNING: CWin32DirectSound::GetSpace - buffer underrun - W:51192, P:39408, O:44136.
14:30:16.495 T:12052 WARNING: CWin32DirectSound::GetSpace - buffer underrun - W:30120, P:16184, O:19464.
14:30:16.495 T:12052 WARNING: CWin32DirectSound::GetSpace - buffer underrun - W:37176, P:25680, O:35408.
14:30:47.174 T:2624  NOTICE: [Artist Slideshow] script version 2.1.1 started
14:30:47.174 T:2624  NOTICE: [Artist Slideshow] debug logging set to false
14:31:07.330 T:1596   ERROR: CCurlFile::FillBuffer - Failed: Transferred a partial file(18)
14:31:07.330 T:1596 WARNING: CCurlFile::FillBuffer - Reconnect, (re)try 1
14:31:35.532 T:2624   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: (2, 'Le fichier sp\xe9cifi\xe9 est introuvable', u'C:\\Users\\mediacenter\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.artistslideshow\\ArtistSlideshow\\JOE COCKER ')
                                            Traceback (most recent call last):
                                              File "C:\Users\mediacenter\AppData\Roaming\Kodi\addons\script.artistslideshow\default.py", line 1367, in <module>
                                                slideshow = Main()
                                              File "C:\Users\mediacenter\AppData\Roaming\Kodi\addons\script.artistslideshow\default.py", line 186, in __init__
                                                self._trim_cache()
                                              File "C:\Users\mediacenter\AppData\Roaming\Kodi\addons\script.artistslideshow\default.py", line 940, in _trim_cache
                                                folders.sort( key=lambda x: os.path.getmtime( os.path.join ( cache_root, x ) ), reverse=True )
                                              File "C:\Users\mediacenter\AppData\Roaming\Kodi\addons\script.artistslideshow\default.py", line 940, in <lambda>
                                                folders.sort( key=lambda x: os.path.getmtime( os.path.join ( cache_root, x ) ), reverse=True )
                                              File "C:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.601.0_x86__4n2hpmxwrvr6p\system\python\Lib\genericpath.py", line 62, in getmtime
                                                return os.stat(filename).st_mtime
                                            WindowsError: (2, 'Le fichier sp\xe9cifi\xe9 est introuvable', u'C:\\Users\\mediacenter\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.artistslideshow\\ArtistSlideshow\\JOE COCKER ')
                                            -->End of Python script error report<--

Thanks. Keep up the good work !

**Comment by chewiiie** [comment] 2018-03-28 12:49
Oh and the skin is Eminence 2.0

**Comment by pkscout** [comment] 2018-03-28 15:31
I'll have to look at it in more detail, but the issue is in the function that trims the cache.  If you go into the AS settings and turn off the advanced option for trimming the size of your download cache, I think that'll resolve the issue for now.

**Comment by pkscout** [comment] 2019-11-11 02:10
The cache trim mechanism has been updated for AS 3.x (which is in early testing now, and this should be fixed.

**Closed by pkscout** 2019-11-11 02:10 UTC
